#!/usr/bin/env bash
# Installs nginx server
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
